# Generated by Django 3.2.9 on 2022-05-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
