# Generated by Django 3.2.9 on 2022-05-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
